package com.onemed1a.backend.controller;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.onemed1a.backend.dto.RecommendationRequest;
import com.onemed1a.backend.model.MediaData;
import com.onemed1a.backend.service.OpenAIService;

/**
 * Controller for handling media recommendations powered by OpenAI.
 *
 * Exposes an endpoint that takes a media name and type,
 * and returns a list of recommended related media items.
 */
@RestController
@RequestMapping("/openai")
public class RecommendationController {
    private final OpenAIService openAIService;

    /**
     * Creates a new RecommendationController with the given service.
     *
     * @param openAIService service used to generate media recommendations
     */
    public RecommendationController(OpenAIService openAIService) {
        this.openAIService = openAIService;
    }

    /**
     * Returns a list of media recommendations generated by OpenAI.
     *
     * @param request the recommendation request containing media type and name
     * @return a response entity containing the list of recommended media items
     */
    @PostMapping("/recommendation")
    public ResponseEntity<List<MediaData>> getRecommendation(@RequestBody RecommendationRequest request) {
        List<MediaData> recs = openAIService.getRecommendation(
            request.getMediaType(),
            request.getMediaName()
        );
    return ResponseEntity.ok(recs);
}
}
